#!/usr/bin/env php
<?php
defined('YII_DEBUG') or define('YII_DEBUG', true);
defined('YII_ENV') or define('YII_ENV', 'test');
// To exit with error code
defined('YII_ENV_TEST') or define('YII_ENV_TEST', false);

require __DIR__ . '/../vendor/autoload.php';
require __DIR__ . '/../vendor/yiisoft/yii2/Yii.php';

Yii::setAlias('@yii/cron', dirname(__DIR__) . '/src');
Yii::setAlias('@tests', __DIR__);

$config = require __DIR__ . '/config/main.php';

$app = new \yii\console\Application($config);
$code = $app->run();
exit($code);